exclude_patterns:
- "tests/"
- "migrations/"
- "migrations_dev/"
- "migrations_test/"
- "node_modules/"
- "**/lib/"
- ".github/"
- "docker/"
- "docs/"
- "docs/"
- "em_web/scripts/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
