language: python
os: linux
dist: focal
jobs:
  include:
    - python: 3.7
      env: TOXV=py37
services:
  - redis
before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl sqlite3
  - pip install tox-travis poetry codecov flask
  - python --version
script:
  - export FLASK_APP=em_web; export FLASK_ENV=test; flask --help
  - export FLASK_APP=em_web; export FLASK_ENV=test; poetry run flask run
  - export FLASK_APP=em_web; export FLASK_ENV=test; poetry run flask cli create_db
  
after_success:
  - codecov
