language: python
os: linux
dist: focal
jobs:
  include:
    - python: 3.7
      env: TOXV=py37
services:
  - redis
before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl sqlite3
  - pip install tox-travis poetry codecov
  - python --version
script:
  - flask --help
  - flask cli create_db
after_success:
  - codecov
