language: generic
os: linux
dist: bionic
jobs:
  include:
    - python: 3.7
      env: TOXV=py37
    - python: 3.8
      env: TOXV=py38
    - python: 3.9
      env: TOXV=py39
before_install:
  - python -m pip install --disable-pip-version-check --quiet poetry tox
  - python --version
  - redis-server --daemonize yes
  - cd /builds/extract-management/extract-management-site/
  - su - postgres -c "/etc/init.d/postgresql start && psql --command \"CREATE USER webapp WITH SUPERUSER PASSWORD 'nothing';\"  && createdb -O webapp em_web_test"

script:
 - tox -e clean,$TOXV,cov
after_success:
  - codecov
