language: python
os: linux
dist: bionic
jobs:
  include:
    - python: 3.7
      env: TOXV=py37
    - python: 3.8
      env: TOXV=py38
    - python: 3.9
      env: TOXV=py39
services:
  - redis-server
  - postgres
before_install:
  - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
  - pip install tox-travis
  - pip install --disable-pip-version-check --quiet poetry tox
  - python --version
  - redis-server --daemonize yes
  - psql --command "CREATE USER webapp WITH SUPERUSER PASSWORD 'nothing';" -U postgres
  - psql --command 'CREATE database em_web_test WITH OWNER webapp;' -U postgres
script:
 - tox -e clean,$TOXV,cov
after_success:
  - codecov
