language: generic
os: linux
dist: xenial
jobs:
  include:
    - python: 3.7
      env: TOXV=py37
    - python: 3.8
      env: TOXV=py38
    - python: 3.9
      env: TOXV=py39
before_install:
  - apt-get update -qq && apt-get install -y --no-install-recommends apt-utils curl pkg-config
  - apt-get install -y \
    git \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-dev \
    python3-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libxmlsec1-openssl \
    libsasl2-dev \
    libldap2-dev \
    libssl-dev \
    unixodbc \
    unixodbc-dev \
    redis-server \
    postgresql \
    postgresql-contrib
  - python -m pip install --disable-pip-version-check --quiet poetry tox
  - python --version
  - redis-server --daemonize yes
  - cd /builds/extract-management/extract-management-site/
  - su - postgres -c "/etc/init.d/postgresql start && psql --command \"CREATE USER webapp WITH SUPERUSER PASSWORD 'nothing';\"  && createdb -O webapp em_web_test"

script:
 - tox -e clean,$TOXV,cov
after_success:
  - codecov
