name: Demo

on:
  schedule:
  - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: Techmmunity/docker-heroku-deploy@v1.0.0
      with:
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        email: ${{ secrets.HEROKU_EMAIL }}
        dockerfile_name: nodb.Dockerfile
