# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
name: "CI"

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: christopherpickering/extract-management-2-python39-test
    steps:
      - name: build
        uses: actions/checkout@v1
        run: tox -e docs

      - name: docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
